"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { projects } from "./data";
import { avatarNeeleshPng, fireIconSvg, projectSupplyChainPng } from "@/assets";

export default function ProjectsPage() {
  const [activeFilter, setActiveFilter] = useState("All Projects");
  const visibleProjects = projects.filter((_, index) => activeFilter === "All Projects" || (activeFilter === "Trending" ? index % 2 === 0 : index > 1));

  return (
    <div className="flex w-full flex-col gap-5 text-left">
      <div><h2 className="text-[32px] leading-10 text-[#191C1E]">Explore Student&apos;s Projects</h2><p className="mt-1 text-[14px] leading-5 text-[#444655]">Mobile and web applications, innovative dashboards and more - all built by students like you</p></div>
      <div className="flex items-center gap-2">{["All Projects", "Trending", "Newest"].map((filter) => <button key={filter} type="button" onClick={() => setActiveFilter(filter)} className={`rounded-full border px-4 py-2 text-[12px] leading-4 ${activeFilter === filter ? "border-[#2B50EC] bg-[#2B50EC] text-white" : "border-[#C4C5D8] bg-[#ECEEF0] text-[#444655] hover:bg-[#E1E4E8]"}`}>{filter}</button>)}</div>
      <div className="grid w-full grid-cols-1 items-start gap-5 lg:grid-cols-12">
        <div className="lg:col-span-8"><div className="grid grid-cols-1 gap-5 sm:grid-cols-2">{visibleProjects.map((project) => <Link href={`/dashboard/projects/${project.slug}`} key={project.slug} className="group flex flex-col overflow-hidden rounded-lg border border-[#E0E3E5] bg-white transition-shadow hover:shadow-[0px_8px_20px_rgba(15,23,42,0.1)]"><div className="relative h-36 bg-[#ECEEF0]"><Image src={project.hero} alt={project.title} fill className="object-cover transition-transform duration-300 group-hover:scale-105" sizes="(max-width: 1024px) 100vw, 33vw" /><span className="absolute left-3 top-3 rounded bg-white/90 px-2 py-1 text-[10px] leading-3 text-[#0032C4]">{project.tags[0]}</span></div><div className="p-4"><div className="mb-2 flex flex-wrap gap-1.5">{project.tags.map((tag) => <span key={tag} className="rounded bg-[rgba(222,225,255,0.5)] px-1.5 py-1 text-[10px] leading-3 text-[#0032C4]">{tag}</span>)}</div><h3 className="pb-1 text-[13px] font-semibold leading-5 text-[#191C1E]">{project.title}</h3><p className="min-h-[60px] pb-4 text-[11px] leading-4 text-[#444655]">{project.description}</p><div className="flex items-center gap-2 border-t border-[rgba(196,197,216,0.5)] pt-3"><Image src={avatarNeeleshPng} alt="Consistency AI student" width={24} height={24} className="rounded-full border border-[#C4C5D8]" /><p className="text-[11px] leading-4 text-[#191C1E]">Consistency AI</p></div></div></Link>)}</div></div>
        <aside className="flex flex-col gap-5 lg:col-span-4"><section className="rounded-lg bg-[#0035CE] p-5 text-white shadow-[0px_12px_32px_0px_rgba(43,80,236,0.2)]"><h4 className="text-[13px] leading-5">Project Ecosystem</h4><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-md border border-white/20 bg-white/10 p-3"><p className="text-[11px] leading-4 text-[#DEE1FF]">Total<br />Projects</p><p className="mt-1 text-[13px] leading-5">1,248</p></div><div className="rounded-md border border-white/20 bg-white/10 p-3"><p className="text-[11px] leading-4 text-[#DEE1FF]">Active<br />Mentees</p><p className="mt-1 text-[13px] leading-5">892</p></div></div></section><section className="rounded-lg border border-[#E0E3E5] bg-white p-5"><div className="flex items-center gap-2"><Image src={fireIconSvg} alt="" width={14} height={16} /><h4 className="text-[13px] leading-5 text-[#191C1E]">Project of the Month</h4></div><div className="relative mt-3 h-28 overflow-hidden rounded-md"><Image src={projectSupplyChainPng} alt="Global Supply Chain Tracker" fill className="object-cover" sizes="25vw" /><div className="absolute inset-0 flex items-end bg-gradient-to-t from-black/60 to-transparent p-3"><span className="text-[12px] text-white">Global Supply Chain Tracker</span></div></div><p className="mt-3 text-[11px] leading-4 text-[#444655]">An exceptional implementation of real-time logistics tracking utilizing WebSockets and interactive maps.</p><button type="button" className="mt-4 w-full rounded-md border border-[#0035CE] px-2 py-2 text-[11px] leading-4 text-[#0035CE] hover:bg-[#EEF2FF]">View Case Study</button></section></aside>
      </div>
    </div>
  );
}